name: Autobahn Test Suite

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.24.1"

            - name: Start wsgo server
              run: |
                  go build -o wsgo
                  ./wsgo &
                  # Give the server time to start
                  sleep 5

            - name: Run Autobahn Test Suite
              run: bash ./autobahn.sh

            - name: Upload test results as artifact
              uses: actions/upload-artifact@v3
              with:
                  name: autobahn-test-reports
                  path: autobahn/reports/servers/

            - name: Setup Pages
              if: github.ref == 'refs/heads/main'
              uses: actions/configure-pages@v3

            - name: Upload pages artifact
              if: github.ref == 'refs/heads/main'
              uses: actions/upload-pages-artifact@v2
              with:
                  path: autobahn/reports/servers/

            - name: Deploy to GitHub Pages
              if: github.ref == 'refs/heads/main'
              id: deployment
              uses: actions/deploy-pages@v2
